inherit_from: .rubocop_todo.yml

require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake

AllCops:
  NewCops: enable

Layout/LineLength:
  Max: 135

Lint/EmptyClass:
  AllowComments: true

Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/ParameterLists:
  MaxOptionalParameters: 4
Metrics/PerceivedComplexity:
  Enabled: false

Minitest/AssertPredicate:
  Enabled: false
Minitest/RefutePredicate:
  Enabled: false

Performance/RedundantBlockCall:
  Enabled: false # for readability

Style/Documentation:
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/FormatStringToken:
  EnforcedStyle: template
Style/GlobalVars:
  AllowedVariables:
    - $load_god
    - $run
Style/NumericLiteralPrefix:
  EnforcedOctalStyle: zero_only
Style/NumericLiterals:
  Enabled: false
Style/NumericPredicate:
  EnforcedStyle: comparison
Style/SymbolArray:
  EnforcedStyle: brackets
