source 'https://rubygems.org'
gemspec

gem 'redcarpet'
gem 'sanitize'

gem 'activesupport'
gem 'airbrake'
gem 'daemons'
gem 'dike'
gem 'gollum'
gem 'i18n'
gem 'json'
gem 'minitest'
gem 'mocha'
gem 'mustache'
gem 'nokogiri'
gem 'prowly'
gem 'rake'
gem 'rdoc'
gem 'statsd-ruby'
gem 'twitter'

gem 'net-smtp' if RUBY_VERSION >= '3.1'

gem 'rubocop'
gem 'rubocop-minitest'
gem 'rubocop-performance'
gem 'rubocop-rake'
gem 'simplecov-cobertura', '~> 2.0'
